### ISSUE TITLE
Plan to integrate kolach/tmux-temp

### ISSUE THREAD

**Issue by narugit** [narugit/tmux-temp-mac#1]
I have a plan to integrate this repository into [kolach/tmux-temp](https://github.com/kolach/tmux-temp) (I really appreciate his/her awesome plugin!) so that we can unify `.tmux.conf` in Linux and Mac.

**Comment by h0adp0re** [comment]
That's a very good idea, do you have a status update on that?

**Comment by narugit** [comment]
@R0LA1mRifcF8yAkk 
I'm really sorry for slow reply.

Actually, there are no update.

**Comment by narugit** [comment]
@h0adp0re 
Sorry for late update. I have integrated in here.
https://github.com/narugit/tmux-temp

I have submitted PR for original repo.
https://github.com/kolach/tmux-temp/pull/7

**Comment by h0adp0re** [comment]
Thank you! I see your PR is now merged and https://github.com/kolach/tmux-temp can be used.
